# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:


- task: PowerShell@2
  displayName: Delaying current task
  inputs: 
    targetType: inline
    script: 
      Start-Sleep(20)

   
- task: PowerShell@2
  displayName: Powershell-Variable Creation
  inputs:
    targetType: 'inline'
    script: 
      ipconfig | set-content -path ".\ipconfig.txt"
      get-content(".\ipconfig.txt")
      

- task: PowerShell@2
  displayName: Powershell-Value check
  condition: and(succeeded(), ne(variables[ 'ENV:sampletest' ], 'lokeshkumar'))
  inputs: 
    targetType: inline
    script: write-host("Checking")
            
    
