# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  repositories:
  - repository: lokeshkumar
    type: github
    endpoint: github.com_lokesh2698(1)
    name:  lokesh2698/lokeshkumar


trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

   
- task: PowerShell@2
  displayName: Powershell-Variable Creation
  inputs:
    targetType: filePath
    filePath: lokeshkumar/script.ps1
    
      

- task: PowerShell@2
  displayName: Powershell-Value check
  condition: and(succeeded(), ne(variables[ 'ENV:sampletest' ], 'lokeshkumar'))
  inputs: 
    targetType: inline
    script: write-host("Checking")
            
    
